# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d576a8fe60bcadc19a9019b253c0797ef333ea2d1f208ff4ed027a8bb53532631f5ecf93263eb7b88e6adb5ad03dcca68f139eace7c1cb99d0c86e5bb0ba9122

test:
  secret_key_base: 5e5a70e38bf296ca014295d0720518786e3394b1d06d4dfd7801dff05d90c6e7b005b3385d7c1542ae62239d834910e7c53629bbec382c912307eedeec0e4069

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
